### Question 00
import necessary libraries in the box below

In [42]:
import numpy as np

### Question 01
Create a NumPy array from [1,2,3, ..., 12].

In [43]:
array_01 = np.arange(1,13)

### Question 02
Print the type of array array_01

In [44]:
print(type(array_01))

<class 'numpy.ndarray'>


### Question 03
Reshape array_01 into 3 x 4 matrix.

In [45]:
array_03 = array_01.reshape(3,4)
array_03

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

### Question 04
Get the length of the array_03.

In [46]:
print(array_03.size)

12


### Question 05
Print the second element of the second row in array_03.

In [47]:
print(array_03[1,1])

6


### Question 06
Multiply all elements of array_03 by 2.

In [48]:
array_06 = array_03 * 2
array_06

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24]])

### Question 07
Add 5 to all elements of array_06.

In [49]:

print(array_06 + 5)

[[ 7  9 11 13]
 [15 17 19 21]
 [23 25 27 29]]


### Question 07
Create an array of 18 zeros.

In [50]:
array_07 = np.zeros(18)
array_07

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0.])

### Question 08
Create an array of 20 fours.

In [51]:
array_08 = np.ones(20) * 4
array_08

array([4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4.,
       4., 4., 4.])

### Question 09
Create numbers from 0 to 20.

In [52]:
array_09 = np.arange(20)
array_09

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

### Question 10
Create 24 random numbers between 0 and 1.
Then, Reshape it into matrix with 6 rows.

In [53]:
array_10 = np.random.random(24)
array_10 = array_10.reshape(6,4)
array_10

array([[0.68864577, 0.78999004, 0.68794187, 0.45831356],
       [0.72256498, 0.35739551, 0.91236613, 0.75502426],
       [0.36346401, 0.44156632, 0.68918849, 0.70855547],
       [0.70659892, 0.06113654, 0.72897477, 0.50201754],
       [0.20801221, 0.70318688, 0.31630026, 0.29784693],
       [0.38944369, 0.51565395, 0.96694978, 0.00720455]])

### Question 11
Convert array_08 to String type.

In [54]:
array_11 = array_08.astype(dtype=str)
array_11

array(['4.0', '4.0', '4.0', '4.0', '4.0', '4.0', '4.0', '4.0', '4.0',
       '4.0', '4.0', '4.0', '4.0', '4.0', '4.0', '4.0', '4.0', '4.0',
       '4.0', '4.0'], dtype='<U32')

### Question 12
Find sum of all rows in array_11

In [82]:
array_12 = array_08.reshape(10,2)
print(array_12.sum(axis=0))

[40. 40.]


### Question 13
Find mean of elements of array_10 'in' each row.

In [56]:
array_14 = array_10

print(array_14.min(axis =1))

[0.45831356 0.35739551 0.36346401 0.06113654 0.20801221 0.00720455]


### Question 14
Reverse the array_10.

In [57]:
print(array_10[::-1,::-1])

[[0.00720455 0.96694978 0.51565395 0.38944369]
 [0.29784693 0.31630026 0.70318688 0.20801221]
 [0.50201754 0.72897477 0.06113654 0.70659892]
 [0.70855547 0.68918849 0.44156632 0.36346401]
 [0.75502426 0.91236613 0.35739551 0.72256498]
 [0.45831356 0.68794187 0.78999004 0.68864577]]


### Question 15
Add array [1,2,3,4,5,6] to array_10.

In [59]:
array_15 = np.array([1,2,3,4,5,6])
print(array_10.reshape(4,6) + array_15 )

[[1.68864577 2.78999004 3.68794187 4.45831356 5.72256498 6.35739551]
 [1.91236613 2.75502426 3.36346401 4.44156632 5.68918849 6.70855547]
 [1.70659892 2.06113654 3.72897477 4.50201754 5.20801221 6.70318688]
 [1.31630026 2.29784693 3.38944369 4.51565395 5.96694978 6.00720455]]


### Question 16
Print odd column of array_10

In [64]:

print(array_10[:,0::2])

[[0.68864577 0.68794187]
 [0.72256498 0.91236613]
 [0.36346401 0.68918849]
 [0.70659892 0.72897477]
 [0.20801221 0.31630026]
 [0.38944369 0.96694978]]


### Question 17
Create 3x3 zeros matrix.

In [66]:
array_17 = np.zeros((3,3))
array_17

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

### Question 18
Sort the array_10.

In [67]:
print(np.sort(array_10))

[[0.45831356 0.68794187 0.68864577 0.78999004]
 [0.35739551 0.72256498 0.75502426 0.91236613]
 [0.36346401 0.44156632 0.68918849 0.70855547]
 [0.06113654 0.50201754 0.70659892 0.72897477]
 [0.20801221 0.29784693 0.31630026 0.70318688]
 [0.00720455 0.38944369 0.51565395 0.96694978]]


### Question 19
Transpose the array_10 

In [68]:
print(array_10.T)

[[0.68864577 0.72256498 0.36346401 0.70659892 0.20801221 0.38944369]
 [0.78999004 0.35739551 0.44156632 0.06113654 0.70318688 0.51565395]
 [0.68794187 0.91236613 0.68918849 0.72897477 0.31630026 0.96694978]
 [0.45831356 0.75502426 0.70855547 0.50201754 0.29784693 0.00720455]]


### Question 20
Create even numbers from 11 to 56.

In [77]:
array_20 = np.arange(11,56)
array_20[array_20 % 2 == 0]

array([12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44,
       46, 48, 50, 52, 54])